" Name:         bronzage_black
" Description:  bronzage with black background
" Author:       Maxim Kim <habamax@gmail.com>
" Maintainer:   Maxim Kim <habamax@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: 29.09.2021 14:07:24

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'bronzage_black'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262626', '#d7875f', '#87af87', '#d7d787', '#87afd7', '#d7af5f', '#87d7d7', '#808080', '#4e4e4e', '#d75f5f', '#87af5f', '#afaf5f', '#5f8787', '#af875f', '#87afaf', '#e4e4e4']
  if has('nvim')
    let g:terminal_color_0 = '#262626'
    let g:terminal_color_1 = '#d7875f'
    let g:terminal_color_2 = '#87af87'
    let g:terminal_color_3 = '#d7d787'
    let g:terminal_color_4 = '#87afd7'
    let g:terminal_color_5 = '#d7af5f'
    let g:terminal_color_6 = '#87d7d7'
    let g:terminal_color_7 = '#808080'
    let g:terminal_color_8 = '#4e4e4e'
    let g:terminal_color_9 = '#d75f5f'
    let g:terminal_color_10 = '#87af5f'
    let g:terminal_color_11 = '#afaf5f'
    let g:terminal_color_12 = '#5f8787'
    let g:terminal_color_13 = '#af875f'
    let g:terminal_color_14 = '#87afaf'
    let g:terminal_color_15 = '#e4e4e4'
  endif
  hi Normal guifg=#d0d0d0 guibg=#000000 gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#4e4e4e guibg=NONE gui=NONE cterm=NONE
  hi Statusline guifg=#000000 guibg=#808080 gui=NONE cterm=NONE
  hi StatuslineNC guifg=#808080 guibg=#4e4e4e gui=NONE cterm=NONE
  hi StatuslineTerm guifg=#000000 guibg=#808080 gui=NONE cterm=NONE
  hi StatuslineTermNC guifg=#808080 guibg=#4e4e4e gui=NONE cterm=NONE
  hi VertSplit guifg=#4e4e4e guibg=#4e4e4e gui=NONE cterm=NONE
  hi Pmenu guifg=NONE guibg=#4e4e4e gui=NONE cterm=NONE
  hi PmenuSel guifg=#000000 guibg=#d7d787 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#808080 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#e4e4e4 gui=NONE cterm=NONE
  hi TabLine guifg=#808080 guibg=#4e4e4e gui=NONE cterm=NONE
  hi TabLineFill guifg=#87afaf guibg=#4e4e4e gui=NONE cterm=NONE
  hi TabLineSel guifg=#000000 guibg=#808080 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton guifg=#000000 guibg=#87af87 gui=NONE cterm=NONE
  hi NonText guifg=#4e4e4e guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#4e4e4e guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#262626 gui=NONE cterm=NONE
  hi Visual guifg=#000000 guibg=#87afd7 gui=NONE cterm=NONE
  hi VisualNOS guifg=#000000 guibg=#87afd7 gui=NONE cterm=NONE
  hi LineNr guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi QuickFixLine guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#000000 gui=NONE cterm=NONE
  hi Underlined guifg=#d7d787 guibg=NONE gui=underline cterm=underline
  hi Error guifg=#d75f5f guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#d75f5f guibg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#000000 guibg=#afaf5f gui=NONE cterm=NONE
  hi WarningMsg guifg=#afaf5f guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#87af87 guibg=NONE gui=NONE cterm=NONE
  hi Question guifg=#d7875f guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#000000 guibg=#808080 gui=NONE cterm=NONE
  hi MatchParen guifg=#262626 guibg=#afaf5f gui=NONE cterm=NONE
  hi Search guifg=#262626 guibg=#87af87 gui=NONE cterm=NONE
  hi IncSearch guifg=#262626 guibg=#d7d787 gui=NONE cterm=NONE
  hi WildMenu guifg=#000000 guibg=#d7d787 gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi Cursor guifg=#000000 guibg=#d0d0d0 gui=NONE cterm=NONE
  hi lCursor guifg=#000000 guibg=#d75f5f gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi DiffText guifg=#87d7d7 guibg=#5f8787 gui=NONE cterm=NONE
  hi DiffDelete guifg=#d75f5f guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#d75f5f guibg=NONE guisp=#d75f5f gui=undercurl cterm=underline
  hi SpellCap guifg=#d7875f guibg=NONE guisp=#d7875f gui=undercurl cterm=underline
  hi SpellLocal guifg=#afaf5f guibg=NONE guisp=#afaf5f gui=undercurl cterm=underline
  hi SpellRare guifg=#d7d787 guibg=NONE guisp=#d7d787 gui=undercurl cterm=underline
  hi Comment guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#afaf5f guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#d7d787 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#d7af5f guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#d7875f guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#87af87 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#87af5f guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#87afaf guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#af875f guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#5f8787 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#af875f guibg=NONE gui=NONE cterm=NONE
  hi Tag guifg=#87d7d7 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#87d7d7 guibg=NONE gui=NONE cterm=NONE
  hi Directory guifg=#af875f guibg=NONE gui=bold cterm=bold
  hi Conceal guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Title guifg=#e4e4e4 guibg=NONE gui=bold cterm=bold
  unlet s:t_Co
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=252 ctermbg=16 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi EndOfBuffer ctermfg=239 ctermbg=NONE cterm=NONE
  hi Statusline ctermfg=16 ctermbg=244 cterm=NONE
  hi StatuslineNC ctermfg=244 ctermbg=239 cterm=NONE
  hi StatuslineTerm ctermfg=16 ctermbg=244 cterm=NONE
  hi StatuslineTermNC ctermfg=244 ctermbg=239 cterm=NONE
  hi VertSplit ctermfg=239 ctermbg=239 cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=239 cterm=NONE
  hi PmenuSel ctermfg=16 ctermbg=186 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=244 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=254 cterm=NONE
  hi TabLine ctermfg=244 ctermbg=239 cterm=NONE
  hi TabLineFill ctermfg=109 ctermbg=239 cterm=NONE
  hi TabLineSel ctermfg=16 ctermbg=244 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=16 ctermbg=108 cterm=NONE
  hi NonText ctermfg=239 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=239 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=244 ctermbg=235 cterm=NONE
  hi Visual ctermfg=16 ctermbg=110 cterm=NONE
  hi VisualNOS ctermfg=16 ctermbg=110 cterm=NONE
  hi LineNr ctermfg=244 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=244 ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=235 cterm=NONE
  hi QuickFixLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=16 cterm=NONE
  hi Underlined ctermfg=186 ctermbg=NONE cterm=underline
  hi Error ctermfg=167 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=16 ctermbg=143 cterm=NONE
  hi WarningMsg ctermfg=143 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=108 ctermbg=NONE cterm=NONE
  hi Question ctermfg=173 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=16 ctermbg=244 cterm=NONE
  hi MatchParen ctermfg=235 ctermbg=143 cterm=NONE
  hi Search ctermfg=235 ctermbg=108 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=186 cterm=NONE
  hi WildMenu ctermfg=16 ctermbg=186 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Cursor ctermfg=16 ctermbg=252 cterm=NONE
  hi lCursor ctermfg=16 ctermbg=167 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=238 cterm=NONE
  hi DiffText ctermfg=116 ctermbg=66 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=173 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=143 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=186 ctermbg=NONE cterm=underline
  hi Comment ctermfg=244 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=143 ctermbg=NONE cterm=NONE
  hi Function ctermfg=186 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=179 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi String ctermfg=108 ctermbg=NONE cterm=NONE
  hi Character ctermfg=107 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=109 ctermbg=NONE cterm=NONE
  hi Type ctermfg=137 ctermbg=NONE cterm=NONE
  hi Special ctermfg=66 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=137 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=116 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=116 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=137 ctermbg=NONE cterm=bold
  hi Conceal ctermfg=244 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Title ctermfg=254 ctermbg=NONE cterm=bold
  unlet s:t_Co
  finish
endif

" Background: dark
" Color: foreground #D0D0D0 252
" Color: background #000000 16
" Color: color00    #262626 235
" Color: color08    #4E4E4E 239
" Color: color01    #D7875F 173
" Color: color09    #D75F5F 167
" Color: color02    #87AF87 108
" Color: color10    #87AF5F 107
" Color: color03    #D7D787 186
" Color: color11    #AFAF5F 143
" Color: color04    #87AFD7 110
" Color: color12    #5f8787 66
" Color: color05    #D7AF5F 179
" Color: color13    #AF875F 137
" Color: color06    #87D7D7 116
" Color: color14    #87AFAF 109
" Color: color07    #808080 244
" Color: color15    #E4E4E4 254
" Color: colorDiffA #444444 238
" Color: colorDiffC #444444 238
" Color: colorDiffD #444444 238
" Term colors: color00 color01 color02 color03 color04 color05 color06 color07
" Term colors: color08 color09 color10 color11 color12 color13 color14 color15
" vim: et ts=2 sw=2
