" Name:         gruvbase
" Description:  Simplified version of retro groove colorscheme originally designed by morhetz <morhetz@gmail.com>
" Author:       Maxim Kim <habamax@gmail.com>
" Maintainer:   Maxim Kim <habamax@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: 27.06.2020 19:20:58

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'gruvbase'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#1d2021', '#fb4934', '#b8bb26', '#8ec07c',
          \ '#83a598', '#fabd2f', '#fe8019', '#504945', '#a89984', '#fb4934',
          \ '#b8bb26', '#8ec07c', '#83a598', '#fabd2f', '#fe8019', '#ebdbb2']
    if has('nvim')
      let g:terminal_color_0 = '#1d2021'
      let g:terminal_color_1 = '#fb4934'
      let g:terminal_color_2 = '#b8bb26'
      let g:terminal_color_3 = '#8ec07c'
      let g:terminal_color_4 = '#83a598'
      let g:terminal_color_5 = '#fabd2f'
      let g:terminal_color_6 = '#fe8019'
      let g:terminal_color_7 = '#504945'
      let g:terminal_color_8 = '#a89984'
      let g:terminal_color_9 = '#fb4934'
      let g:terminal_color_10 = '#b8bb26'
      let g:terminal_color_11 = '#8ec07c'
      let g:terminal_color_12 = '#83a598'
      let g:terminal_color_13 = '#fabd2f'
      let g:terminal_color_14 = '#fe8019'
      let g:terminal_color_15 = '#ebdbb2'
    endif
    if get(g:, 'gruvbase_transp_bg', 0)
      hi Normal guifg=#ebdbb2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#ebdbb2 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
    endif
    hi EndOfBuffer guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statusline guifg=#ebdbb2 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi StatuslineNC guifg=#a89984 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi StatuslineTerm guifg=#ebdbb2 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi StatuslineTermNC guifg=#a89984 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#504945 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#1d2021 guibg=#8ec07c guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=NONE guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
    hi TabLine guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=NONE guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
    hi ToolbarLine guifg=#1d2021 guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=NONE guibg=#665c54 guisp=NONE gui=bold cterm=bold
    hi NonText guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#a89984 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    hi CursorColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    hi QuickFixLine guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Underlined guifg=#83a598 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi Error guifg=#ebdbb2 guibg=#fb4934 guisp=NONE gui=NONE cterm=NONE
    hi Todo guifg=#1d2021 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
    hi MatchParen guifg=NONE guibg=#fe8019 guisp=NONE gui=NONE cterm=NONE
    hi Search guifg=#1d2021 guibg=#8ec07c guisp=NONE gui=NONE cterm=NONE
    hi IncSearch guifg=#1d2021 guibg=#d3869b guisp=NONE gui=NONE cterm=NONE
    hi WildMenu guifg=#1d2021 guibg=#8ec07c guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=#ebdbb2 guibg=#79740e guisp=NONE gui=NONE cterm=NONE
    hi DiffChange guifg=#ebdbb2 guibg=#427b58 guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=#ebdbb2 guibg=#b57614 guisp=NONE gui=NONE cterm=NONE
    hi DiffDelete guifg=#a89984 guibg=#79740e guisp=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#83a598 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#fb4934 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Constant guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi String guifg=#b8bb26 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#8ec07c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#fe8019 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Tag guifg=#8ec07c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Delimiter guifg=#a16946 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Type guifg=#fabd2f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Operator guifg=#8ec07c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Directory guifg=#83a598 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Comment guifg=#a89984 guibg=NONE guisp=NONE gui=italic cterm=italic
    hi Conceal guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#fb4934 guibg=NONE guisp=NONE gui=bold cterm=bold
    if !s:italics
      hi Comment gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#f9f5d7', '#9d0006', '#79740e', '#076678',
        \ '#076678', '#b57614', '#af3a03', '#d5c4a1', '#7c6f64', '#9d0006',
        \ '#79740e', '#076678', '#076678', '#b57614', '#af3a03', '#3c3836']
  if has('nvim')
    let g:terminal_color_0 = '#f9f5d7'
    let g:terminal_color_1 = '#9d0006'
    let g:terminal_color_2 = '#79740e'
    let g:terminal_color_3 = '#076678'
    let g:terminal_color_4 = '#076678'
    let g:terminal_color_5 = '#b57614'
    let g:terminal_color_6 = '#af3a03'
    let g:terminal_color_7 = '#d5c4a1'
    let g:terminal_color_8 = '#7c6f64'
    let g:terminal_color_9 = '#9d0006'
    let g:terminal_color_10 = '#79740e'
    let g:terminal_color_11 = '#076678'
    let g:terminal_color_12 = '#076678'
    let g:terminal_color_13 = '#b57614'
    let g:terminal_color_14 = '#af3a03'
    let g:terminal_color_15 = '#3c3836'
  endif
  if get(g:, 'gruvbase_transp_bg', 0)
    hi Normal guifg=#3c3836 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#3c3836 guibg=#f9f5d7 guisp=NONE gui=NONE cterm=NONE
  endif
  hi EndOfBuffer guifg=#d5c4a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statusline guifg=#3c3836 guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi StatuslineNC guifg=#7c6f64 guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi StatuslineTerm guifg=#3c3836 guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi StatuslineTermNC guifg=#7c6f64 guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#d5c4a1 guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=NONE guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#f9f5d7 guibg=#076678 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#7c6f64 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=NONE guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#d5c4a1 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=NONE guibg=#f9f5d7 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#f9f5d7 guibg=#bdae93 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=NONE guibg=#bdae93 guisp=NONE gui=bold cterm=bold
  hi NonText guifg=#d5c4a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#d5c4a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#7c6f64 guibg=#ebdbb2 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#bdae93 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#7c6f64 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#7c6f64 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#ebdbb2 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#ebdbb2 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#ebdbb2 guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=NONE guibg=#ebdbb2 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Underlined guifg=#076678 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi Error guifg=#f9f5d7 guibg=#9d0006 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#3c3836 guibg=#f9f5d7 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#af3a03 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#f9f5d7 guibg=#076678 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#f9f5d7 guibg=#8f3f71 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#f9f5d7 guibg=#076678 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#3c3836 guibg=#b8bb26 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#3c3836 guibg=#8ec07c guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#3c3836 guibg=#fabd2f guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#7c6f64 guibg=#fb4934 guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#076678 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#9d0006 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#8f3f71 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#79740e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#076678 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#af3a03 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#076678 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#af3a03 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#b57614 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#076678 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#076678 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Comment guifg=#7c6f64 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conceal guifg=#7c6f64 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#9d0006 guibg=NONE guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'gruvbase_transp_bg', 0)
      hi Normal ctermfg=187 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=187 ctermbg=234 cterm=NONE
      if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
        set background=dark
      endif
    endif
    hi EndOfBuffer ctermfg=239 ctermbg=NONE cterm=NONE
    hi Statusline ctermfg=187 ctermbg=239 cterm=NONE
    hi StatuslineNC ctermfg=137 ctermbg=239 cterm=NONE
    hi StatuslineTerm ctermfg=187 ctermbg=239 cterm=NONE
    hi StatuslineTermNC ctermfg=137 ctermbg=239 cterm=NONE
    hi VertSplit ctermfg=239 ctermbg=239 cterm=NONE
    hi Pmenu ctermfg=NONE ctermbg=239 cterm=NONE
    hi PmenuSel ctermfg=234 ctermbg=107 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=239 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=137 cterm=NONE
    hi TabLine ctermfg=NONE ctermbg=239 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=239 cterm=NONE
    hi TabLineSel ctermfg=NONE ctermbg=234 cterm=NONE
    hi ToolbarLine ctermfg=234 ctermbg=59 cterm=NONE
    hi ToolbarButton ctermfg=NONE ctermbg=59 cterm=bold
    hi NonText ctermfg=239 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=239 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=137 ctermbg=237 cterm=NONE
    hi Visual ctermfg=NONE ctermbg=59 cterm=NONE
    hi LineNr ctermfg=137 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=137 ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=237 cterm=NONE
    hi QuickFixLine ctermfg=NONE ctermbg=237 cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=109 ctermbg=NONE cterm=underline
    hi Error ctermfg=187 ctermbg=196 cterm=NONE
    hi Todo ctermfg=234 ctermbg=234 cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=208 cterm=NONE
    hi Search ctermfg=234 ctermbg=107 cterm=NONE
    hi IncSearch ctermfg=234 ctermbg=175 cterm=NONE
    hi WildMenu ctermfg=234 ctermbg=107 cterm=NONE
    hi DiffAdd ctermfg=187 ctermbg=100 cterm=NONE
    hi DiffChange ctermfg=187 ctermbg=29 cterm=NONE
    hi DiffText ctermfg=187 ctermbg=172 cterm=NONE
    hi DiffDelete ctermfg=137 ctermbg=100 cterm=NONE
    hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=196 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=175 ctermbg=NONE cterm=NONE
    hi String ctermfg=142 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=107 ctermbg=NONE cterm=NONE
    hi Special ctermfg=208 ctermbg=NONE cterm=NONE
    hi Tag ctermfg=107 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=130 ctermbg=NONE cterm=NONE
    hi Type ctermfg=214 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=107 ctermbg=NONE cterm=NONE
    hi Directory ctermfg=109 ctermbg=NONE cterm=bold
    hi Comment ctermfg=137 ctermbg=NONE cterm=italic
    hi Conceal ctermfg=137 ctermbg=NONE cterm=NONE
    hi Title ctermfg=196 ctermbg=NONE cterm=bold
    if !s:italics
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'gruvbase_transp_bg', 0)
    hi Normal ctermfg=237 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=237 ctermbg=230 cterm=NONE
  endif
  hi EndOfBuffer ctermfg=187 ctermbg=NONE cterm=NONE
  hi Statusline ctermfg=237 ctermbg=187 cterm=NONE
  hi StatuslineNC ctermfg=243 ctermbg=187 cterm=NONE
  hi StatuslineTerm ctermfg=237 ctermbg=187 cterm=NONE
  hi StatuslineTermNC ctermfg=243 ctermbg=187 cterm=NONE
  hi VertSplit ctermfg=187 ctermbg=187 cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=187 cterm=NONE
  hi PmenuSel ctermfg=230 ctermbg=23 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=187 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=243 cterm=NONE
  hi TabLine ctermfg=NONE ctermbg=187 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=187 cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=230 cterm=NONE
  hi ToolbarLine ctermfg=230 ctermbg=144 cterm=NONE
  hi ToolbarButton ctermfg=NONE ctermbg=144 cterm=bold
  hi NonText ctermfg=187 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=187 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=243 ctermbg=187 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=144 cterm=NONE
  hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=243 ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=187 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=187 cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=187 cterm=NONE
  hi QuickFixLine ctermfg=NONE ctermbg=187 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=23 ctermbg=NONE cterm=underline
  hi Error ctermfg=230 ctermbg=124 cterm=NONE
  hi Todo ctermfg=237 ctermbg=230 cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=124 cterm=NONE
  hi Search ctermfg=230 ctermbg=23 cterm=NONE
  hi IncSearch ctermfg=230 ctermbg=126 cterm=NONE
  hi WildMenu ctermfg=230 ctermbg=23 cterm=NONE
  hi DiffAdd ctermfg=237 ctermbg=142 cterm=NONE
  hi DiffChange ctermfg=237 ctermbg=107 cterm=NONE
  hi DiffText ctermfg=237 ctermbg=214 cterm=NONE
  hi DiffDelete ctermfg=243 ctermbg=196 cterm=NONE
  hi Identifier ctermfg=23 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=124 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=126 ctermbg=NONE cterm=NONE
  hi String ctermfg=100 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=23 ctermbg=NONE cterm=NONE
  hi Special ctermfg=124 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=23 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=124 ctermbg=NONE cterm=NONE
  hi Type ctermfg=172 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=23 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=23 ctermbg=NONE cterm=bold
  hi Comment ctermfg=243 ctermbg=NONE cterm=italic
  hi Conceal ctermfg=243 ctermbg=NONE cterm=NONE
  hi Title ctermfg=124 ctermbg=NONE cterm=bold
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: grey   #7c6f64 ~
" Color: red    #9d0006 ~
" Color: green  #79740e ~
" Color: yellow #076678 ~
" Color: blue   #076678 ~
" Color: purple #b57614 ~
" Color: aqua   #af3a03 ~
" Color: orange #8f3f71 ~
" Color: brown  #af3a03 ~
" Color: fg0    #3c3836 ~
" Color: bg0    #f9f5d7 ~
" Color: bg1    #d5c4a1 ~
" Color: folded #ebdbb2 ~
" Color: visual #bdae93 ~
" Color: error  #9d0006 ~
" Color: todo   #f9f5d7 ~
" Color: diff1  #b8bb26 ~
" Color: diff2  #8ec07c ~
" Color: diff3  #fabd2f ~
" Color: diff4  #fb4934 ~
" Term colors: bg0  red green yellow blue purple aqua bg1
" Term colors: grey red green yellow blue purple aqua fg0
" Background: dark
" Color: grey   #a89984 ~
" Color: red    #fb4934 ~
" Color: green  #b8bb26 ~
" Color: yellow #8ec07c ~
" Color: blue   #83a598 ~
" Color: purple #fabd2f ~
" Color: aqua   #fe8019 ~
" Color: orange #d3869b ~
" Color: brown  #a16946 ~
" Color: fg0    #ebdbb2 ~
" Color: bg0    #1d2021 ~
" Color: bg1    #504945 ~
" Color: folded #3c3836 ~
" Color: visual #665c54 ~
" Color: error  #fb4934 ~
" Color: todo   #1d2021 ~
" Color: diff1  #79740e ~
" Color: diff2  #427b58 ~
" Color: diff3  #b57614 ~
" Color: diff4  #79740e ~
" Term colors: bg0  red green yellow blue purple aqua bg1
" Term colors: grey red green yellow blue purple aqua fg0
" vim: et ts=2 sw=2
