" Name:         synoff
" Description:  Comments only
" Author:       Maxim Kim <habamax@gmail.com>
" Maintainer:   Maxim Kim <habamax@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: 09.07.2020 22:37:50

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'synoff'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#202531', '#fa7585', '#a1b56c', '#f7ca88',
        \ '#6aa6ca', '#ba8baf', '#86c1b9', '#333b4f', '#6d7079', '#fa7585',
        \ '#a1b56c', '#f7ca88', '#6aa6ca', '#ba8baf', '#86c1b9', '#dedede']
  if has('nvim')
    let g:terminal_color_0 = '#202531'
    let g:terminal_color_1 = '#fa7585'
    let g:terminal_color_2 = '#a1b56c'
    let g:terminal_color_3 = '#f7ca88'
    let g:terminal_color_4 = '#6aa6ca'
    let g:terminal_color_5 = '#ba8baf'
    let g:terminal_color_6 = '#86c1b9'
    let g:terminal_color_7 = '#333b4f'
    let g:terminal_color_8 = '#6d7079'
    let g:terminal_color_9 = '#fa7585'
    let g:terminal_color_10 = '#a1b56c'
    let g:terminal_color_11 = '#f7ca88'
    let g:terminal_color_12 = '#6aa6ca'
    let g:terminal_color_13 = '#ba8baf'
    let g:terminal_color_14 = '#86c1b9'
    let g:terminal_color_15 = '#dedede'
  endif
  if get(g:, 'synoff_transp_bg', 0)
    hi Normal guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#dedede guibg=#202531 guisp=NONE gui=NONE cterm=NONE
  endif
  hi EndOfBuffer guifg=#333b4f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statusline guifg=#dedede guibg=#333b4f guisp=NONE gui=bold cterm=bold
  hi StatuslineNC guifg=#6d7079 guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi StatuslineTerm guifg=#dedede guibg=#333b4f guisp=NONE gui=bold cterm=bold
  hi StatuslineTermNC guifg=#6d7079 guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#333b4f guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=NONE guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#202531 guibg=#dedede guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#6d7079 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=NONE guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#333b4f guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=NONE guibg=#202531 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#202531 guibg=#394e71 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=NONE guibg=#394e71 guisp=NONE gui=bold cterm=bold
  hi NonText guifg=#333b4f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#333b4f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#6d7079 guibg=#262b37 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#394e71 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#6d7079 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#6d7079 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#262b37 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#262b37 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#262b37 guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=NONE guibg=#262b37 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Underlined guifg=#dedede guibg=NONE guisp=NONE gui=underline cterm=underline
  hi Error guifg=#202531 guibg=#ea7a80 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#dedede guibg=#757012 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#6d7079 guibg=#dedede guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#202531 guibg=#6d7079 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#202531 guibg=#dedede guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#202531 guibg=#dedede guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#294929 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#4f4719 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#2f2f09 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#6d7079 guibg=#492929 guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#dedede guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#dedede guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Comment guifg=#6d7079 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conceal guifg=#6d7079 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#dedede guibg=NONE guisp=NONE gui=bold cterm=bold
  hi lCursor guifg=NONE guibg=#ea7a80 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'synoff_transp_bg', 0)
    hi Normal ctermfg=253 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=253 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
  endif
  hi EndOfBuffer ctermfg=237 ctermbg=NONE cterm=NONE
  hi Statusline ctermfg=253 ctermbg=237 cterm=bold
  hi StatuslineNC ctermfg=242 ctermbg=237 cterm=NONE
  hi StatuslineTerm ctermfg=253 ctermbg=237 cterm=bold
  hi StatuslineTermNC ctermfg=242 ctermbg=237 cterm=NONE
  hi VertSplit ctermfg=237 ctermbg=237 cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=235 ctermbg=253 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=237 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=242 cterm=NONE
  hi TabLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=235 cterm=NONE
  hi ToolbarLine ctermfg=235 ctermbg=60 cterm=NONE
  hi ToolbarButton ctermfg=NONE ctermbg=60 cterm=bold
  hi NonText ctermfg=237 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=237 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=242 ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=60 cterm=NONE
  hi LineNr ctermfg=242 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=242 ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=235 cterm=NONE
  hi QuickFixLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=253 ctermbg=NONE cterm=underline
  hi Error ctermfg=235 ctermbg=174 cterm=NONE
  hi Todo ctermfg=253 ctermbg=58 cterm=NONE
  hi MatchParen ctermfg=242 ctermbg=253 cterm=NONE
  hi Search ctermfg=235 ctermbg=242 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=253 cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=253 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=22 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=58 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffDelete ctermfg=242 ctermbg=52 cterm=NONE
  hi Identifier ctermfg=253 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=253 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=253 ctermbg=NONE cterm=NONE
  hi String ctermfg=253 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=253 ctermbg=NONE cterm=NONE
  hi Special ctermfg=253 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=253 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=253 ctermbg=NONE cterm=NONE
  hi Type ctermfg=253 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=253 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=253 ctermbg=NONE cterm=bold
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Conceal ctermfg=242 ctermbg=NONE cterm=NONE
  hi Title ctermfg=253 ctermbg=NONE cterm=bold
  hi lCursor ctermfg=NONE ctermbg=174 cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: grey   #6d7079 ~
" Color: fg0    #dedede ~
" Color: bg0    #202531 ~
" Color: bg1    #333b4f ~
" Color: folded #262b37 ~
" Color: visual #394e71 ~
" Color: error  #ea7a80 ~
" Color: todo   #757012 ~
" Color: diff1  #294929 ~
" Color: diff2  #4f4719 ~
" Color: diff3  #2f2f09 ~
" Color: diff4  #492929 ~
" Color: term01 #fa7585 204
" Color: term02 #a1b56c 107
" Color: term03 #f7ca88 222
" Color: term04 #6aa6ca 74
" Color: term05 #ba8baf 139
" Color: term06 #86c1b9 116
" Term colors: bg0  term01 term02 term03 term04 term05 term06 bg1
" Term colors: grey term01 term02 term03 term04 term05 term06 fg0
" vim: et ts=2 sw=2
